### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by real-prospect** [yandex-money/yandex-money-ycms-opencart3#79]
Здравствуйте. Установил модуль на opencart 3.0.3.6 и после нажатия кнопки редактирования модуля получаю ошибку. Проверял на двух серверах. На версии opencart 3.0.3.2 модуль успешно обновился до версии 1.7.1 и работает.

Fatal error: Uncaught Twig\Error\LoaderError: Template "extension/payment/yandex_money/kassa.twig" is not defined in "extension/payment/yandex_money.twig" at line 46. in /var/www/pw1/data/www/oc_test_storage/vendor/twig/twig/src/Loader/ArrayLoader.php:70 Stack trace: #0 /var/www/pw1/data/www/oc_test_storage/vendor/twig/twig/src/Environment.php(299): Twig\Loader\ArrayLoader->getCacheKey('extension/payme...') #1 /var/www/pw1/data/www/oc_test_storage/vendor/twig/twig/src/Environment.php(381): Twig\Environment->getTemplateClass('extension/payme...') #2 /var/www/pw1/data/www/oc_test_storage/vendor/twig/twig/src/Template.php(333): Twig\Environment->loadTemplate('extension/payme...', NULL) #3 /var/www/pw1/data/www/oc_test_storage/cache/template/84/8423b65bc64abafa7992b7af8b31b7ed1d8aea9bc6435bdff791cbfd8971b09e.php(170): Twig\Template->loadTemplate('extension/payme...', 'extension/payme...', 46) #4 /var/www/pw1/data/www/oc_test_storage/vendor/twig/twig/src/Template.php(405): __TwigTemplate_98d98c4b865162d2ab9048590b5fb436d96988b in /var/www/pw1/data/www/oc_test_storage/vendor/twig/twig/src/Loader/ArrayLoader.php on line 70

**Comment by ostulov** [comment]
Добрый день!

Подобная ошибка может возникать, если не хватает прав на запись в каталоге кэша.

**Comment by real-prospect** [comment]
Вы не подскажите как дать права?

**Comment by real-prospect** [comment]
Точнее какому каталогу какие права нужны?

**Comment by real-prospect** [comment]
Выставил права на все файлы и папки 777, результат тот же. Fatal error.

**Comment by ostulov** [comment]
Добрый день!

Пришлите, пожалуйста, доступы к админпанели сайта с проблемой и к ftp на почту cms@yamoney.ru. Попробуем проверить.
Перед предоставлением доступов обязательно сделайте бэкап!

**Comment by ostulov** [comment]
Ошибка связана с особенностями Opencart версии 3.0.3.6

Порядок действий для исправления ошибки:
в файле system/library/template/twig.php
нужно заменить строку
$loader = new \Twig\Loader\ArrayLoader(array($filename . '.twig' => $code));
на
 $loader1 = new \Twig_Loader_Array(array($filename . '.twig' => $code));
 $loader2 = new \Twig_Loader_Filesystem(array(DIR_TEMPLATE)); 
 $loader = new \Twig_Loader_Chain(array($loader1, $loader2));
Затем очистить папку storage/cache и переустановить модификатор модуля.
